parameters:
- name: ENV
  displayName: 'Environment'
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'prod'

- name: ACTION
  displayName: 'Action'
  type: string
  default: 'apply'
  values:
    - 'apply'
    - 'destroy'

trigger:
- main

pr:
- '*'

pool:
  name: 'Ado Pool'

variables:
  AWS_SERVICE_CONNECTION: 'ado_terraform'
  ACTION: ${{ parameters.ACTION }}  # Capture the ACTION parameter as a variable

stages:
- stage: InitAndPlan
  jobs:
  - job: TerraformInitAndPlan
    displayName: 'Terraform Init and Plan'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip
      displayName: 'Install unzip'

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        backendServiceAWS: $(AWS_SERVICE_CONNECTION)
        backendAWSBucketName: 'terraform-nada'
        backendAWSKey: 'terraform.tfstate'
      displayName: 'Terraform Init'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'plan'
        backendServiceAWS: $(AWS_SERVICE_CONNECTION)
        backendAWSBucketName: 'terraform-nada'
        backendAWSKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        commandOptions: '-var-file=${{ parameters.ENV }}.tfvars'
      displayName: 'Terraform Plan'

- stage: Apply
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Merge'), eq(variables['ACTION'], 'apply'))
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'apply'
        backendServiceAWS: $(AWS_SERVICE_CONNECTION)
        backendAWSBucketName: 'terraform-nada'
        backendAWSKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        commandOptions: '-auto-approve -var-file=${{ parameters.ENV }}.tfvars'
      displayName: 'Terraform Apply'

- stage: Destroy
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Merge'), eq(variables['ACTION'], 'destroy'))
  jobs:
  - job: TerraformDestroy
    displayName: 'Terraform Destroy'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'destroy'
        backendServiceAWS: $(AWS_SERVICE_CONNECTION)
        backendAWSBucketName: 'terraform-nada'
        backendAWSKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        commandOptions: '-auto-approve -var-file=${{ parameters.ENV }}.tfvars'
      displayName: 'Terraform Destroy'
